// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddTask: typeof import('./components/Timer/AddTask.vue')['default']
    EndPomos: typeof import('./components/Timer/EndPomos.vue')['default']
    MobileAlarm: typeof import('./components/Modals/MobileAlarm.vue')['default']
    MObileAlarm: typeof import('./components/Settings/MObileAlarm.vue')['default']
    Modal: typeof import('./components/Modals/Modal.vue')['default']
    ModalColor: typeof import('./components/Modals/ModalColor.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBreaks: typeof import('./components/Timer/TheBreaks.vue')['default']
    TheEdit: typeof import('./components/Timer/TheEdit.vue')['default']
    TheEditAdd: typeof import('./components/Timer/TheEditAdd.vue')['default']
    TheEditV: typeof import('./components/Timer/TheEdit-v.vue')['default']
    TheFinish: typeof import('./components/Timer/TheFinish.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheIntegration: typeof import('./components/Settings/TheIntegration.vue')['default']
    TheLogin: typeof import('./components/TheLogin.vue')['default']
    TheMain: typeof import('./components/TheMain.vue')['default']
    TheModalColor: typeof import('./components/Settings/TheModalColor.vue')['default']
    TheNotifation: typeof import('./components/Settings/TheNotifation.vue')['default']
    TheNotification: typeof import('./components/Settings/TheNotification.vue')['default']
    TheSettings: typeof import('./components/Settings/TheSettings.vue')['default']
    TheSound: typeof import('./components/Settings/TheSound.vue')['default']
    TheTask: typeof import('./components/Settings/TheTask.vue')['default']
    TheTasks: typeof import('./components/Timer/TheTasks.vue')['default']
    TheTheme: typeof import('./components/Settings/TheTheme.vue')['default']
    TheTimer: typeof import('./components/Timer/TheTimer.vue')['default']
    TheTimerSetting: typeof import('./components/Settings/TheTimerSetting.vue')['default']
    Todoist: typeof import('./components/Modals/Todoist.vue')['default']
    Webhook: typeof import('./components/Modals/Webhook.vue')['default']
  }
}
